import './globals.css';
import type { Metadata } from 'next';

import Sidebar from './components/Sidebar';
import Titlebar from './components/Titlebar';
import Header from './components/Header';
import Explorer from './components/Explorer';
import TabBar from './components/TabBar';
import Footer from './components/Footer';
import { ExplorerToggleProvider } from './context/explorer-toggle-context';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="theme-bearded-arc">
      <body>
        <ExplorerToggleProvider>
          <Titlebar />
          <Header />
          <div className="flex">
            <Sidebar />
            <Explorer />
            <div className="w-full flex flex-col">
              <TabBar />
              <main
                id="main-editor"
                className="p-8 flex-1 overflow-y-auto scroll-smooth bg-mainBg text-bgText"
              >
                <div className="flex-1 p-4">{children}</div>
              </main>
            </div>
          </div>
          <Footer />
        </ExplorerToggleProvider>
      </body>
    </html>
  );
}
