import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Sidebar } from "./components/Sidebar";
import Titlebar from "./components/Titlebar";
import Header from "./components/Header";
import Explorer from "./components/Explorer";
import TabBar from "./components/TabBar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="theme-bearded-arc">
      <body>
        <Titlebar />
        <Header />
        <div className="flex">
          <Sidebar />
          <Explorer />
          <div className="w-full">
            <TabBar />
            <main
              id="main-editor"
              className="p-8 flex-1 h-[85vh] overflow-y-auto scroll-smooth bg-mainBg text-bgText"
            >
              <div className="w-3/4 p-4">{children}</div>
            </main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
